---
title: "RWorksheet_Tolentino#2"
author: "Aaron Joshua Tolentino"
date: "2023-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r number1}
sequence <- -5:5
sequence

```
```{r number1b}
x <- 1:7
x
```
```{r number2}
seq(1, 3, by=0.2)
```
```{r number3}
ages <-c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
           22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
           24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
           18)
age2 <- ages[3]
age2
```
```{r number3b}
doubleElement <-ages[c(2,4)]
doubleElement
```
```{r number3c}
exclude <- ages[-c(4, 12)]
exclude
```

```{r number4}
x <- c("first"=3, "second"=0, "third"=9)
names(x)
x[c("first", "third")]
```

```{r number5}
x <- -3:2
x
x[2] <- 0
x
```
```{r number6a}
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

df <- data.frame(Month = month, 
                 Price_per_liter = price_per_liter,
                 Purchase_quantity = purchase_quantity)

df_transposed <- t(df)
df_vertical <- as.data.frame(df_transposed)
df_vertical
```

```{r number6b}
liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase <- c(25, 30, 40, 50, 10, 45)
expenditure_mean <- weighted.mean(liter, purchase)
expenditure_mean
```
```{r number7}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
          sd(rivers), min(rivers), max(rivers))
data
```
```{r number8a}
TopCelebrity <- data.frame (
PowerRanking = 1:25,
CelebrityName = c("Tom Cruise" , "Rolling Stones", "Oprah Winfrey", "U2","Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant"),
Pay = c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
)
TopCelebrity
```
```{r number8b}
NewRanking <- replace(TopCelebrity$PowerRanking, 19, 15)
NewPay <- replace(TopCelebrity$Pay, 19, 90)

Newtopceleb <- data.frame (
PowerRanking = NewRanking, TopCelebrity$CelebrityName, Pay = NewPay)
Newtopceleb
```
```{r number8c}
install.packages("writexl")
library(writexl)
write_xlsx(TopCelebrity, path = "PowerRanking.xlsx")
write.csv(TopCelebrity, file = "PowerRanking.csv", row.names = FALSE)
```
```{r number8d}
subset_data <- TopCelebrity[10:20, ]
save(subset_data, file = "Ranks.RData")
print(subset_data)
```
```{r number9a}
library(readxl)
ExcelDta <- read_excel("Worksheet#2/hotels-vienna.xlsx")
ExcelDta
```
```{r number9b}
dimensions <- dim(ExcelDta)
dimensions
```
```{r number9c}
selected_columns <- ExcelDta[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
head(selected_columns, n = nrow(selected_columns))
```
```{r number9d}
save(selected_columns, file = "new.RData")
```

```{r number9e}
load("new.RData")
head(selected_columns)
tail(selected_columns)
```

```{r number10a}
vegetables <- c("Carrot", "Broccoli", "Spinach", "Tomato", "Cucumber", "Bell Pepper", "Eggplant", "Zucchini", "Kale", "Asparagus")
vegetables
```

```{r number10b}
vegetables <- c(vegetables, "Cauliflower", "Mushroom")
vegetables
```

```{r number10c}
vegetables <- append(vegetables, c("Sweet Potato", "Cabbage", "Radish", "Artichoke"), after = 5)
num_datapoints <- length(vegetables)
vegetables
cat("Number of datapoints:", num_datapoints, "\n")
```

```{r number10d}
vegetables <- vegetables[-c(5, 10, 15)]
num_vegetables_left <- length(vegetables)
vegetables
cat("Number of vegetables left:", num_vegetables_left, "\n")
```
