---
output:
  pdf_document: default
  html_document: default
---
#1. VECTORS
#a.
first_eleven <- LETTERS[1:11]
first_eleven

#b.
odd_letters <- LETTERS[seq(1,25,2)]
odd_letters

#c.
vowels <- c(letters[which(letters %in% c("a","e","i","o","u"))], 
            LETTERS[which(LETTERS %in% c("A","E","I","O","U"))])
vowels

#d.
last5letter <- tail(letters, 5)
last5letter


#e.
letterbetween15to24 <- letters[15:24]
letterbetween15to24


#2.
#a. 

city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

#b. 

temp <- c(42, 39, 34, 34, 30, 27)
temp


#c. 

df <- data.frame(city, temp)
df
#d. 

names(df) <- c("City", "Temperature")
df
#e. 
str(df)

#f.
df[3:4,]


#g. 
highest_temp_city <- df$City[which.max(df$Temperature)]
lowest_temp_city <- df$City[which.min(df$Temperature)]
highest_temp_city 
lowest_temp_city 

#2 MATRICES
#a. 
m <- matrix(c(1:8,11:14),ncol=4,nrow=3)
m
# Output:
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   12
[2,]    2    5    8   13
[3,]    3    6   11   14


#b. 
matrix(c(1:8,11:14),ncol=4,nrow=3) * 2
# Output:
     [,1] [,2] [,3] [,4]
[1,]    2    8   14   24
[2,]    4   10   16   26
[3,]    6   12   22   28


#c. 
matrix(c(1:8,11:14),ncol=4,nrow=3)[2,]
# Output:
[1] 2 5 8 13

#d. 
matrix(c(1:8,11:14),ncol=4,nrow=3)[1:2,c(3,4)]
# Output:
     [,1] [,2]
[1,]    7   12
[2,]    8   13

#e. 
matrix(c(1:8,11:14),ncol=4,nrow=3)[3,c(2,3)]
# Output:
[1] 6 11

#f. 
matrix(c(1:8,11:14),ncol=4,nrow=3)[,4]
# Output:
[1] 12 13 14

#g. 
mat <- matrix(c(1:8,11:14)*2,ncol=4,nrow=3)
rownames(mat) <- c("isa","dalawa","tatlo")
colnames(mat) <- c("uno","dos","tres","quatro")
mat
# Output:
       uno dos tres quatro
isa      1   4    7     12
dalawa   2   5    8     13
tatlo    3   6    11    14

#h. 

dim(m) <- c(6,2)
m

# Output:
     [,1] [,2]
[1,]    1   7
[2,]    2   8
[3,]    3   11
[4,]    4   12
[5,]    5   13
[6,]    6   14



#3. ARRAYS
#A
values <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
array_3d <- array(values, dim = c(2, 4, 3))
values
array_3d
#Output
, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    7    9
[2,]    2    6    8    0

, , 2

     [,1] [,2] [,3] [,4]
[1,]    3    5    1    3
[2,]    4    1    2    6

, , 3

     [,1] [,2] [,3] [,4]
[1,]    7    9    3    5
[2,]    8    0    4    1


#B: The array has three dimensions.

#C
dimnames(array_3d) <- list(c("a", "b"), LETTERS[1:4], c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
#Output
, , 1st-Dimensional Array

  A B C D
a 1 3 7 9
b 2 6 8 0

, , 2nd-Dimensional Array

  A B C D
a 3 5 1 3
b 4 1 2 6

, , 3rd-Dimensional Array

  A B C D
a 7 9 3 5
b 8 0 4 1
